### ISSUE TITLE
When creating a tree list does not update automatically

### ISSUE THREAD

**Issue by arol** [bienmag/oakmap#65]
## Expected Behavior
When I create a tree I expect the list of my trees to list the newly create one, or to redirect me to the new tree page.

## Current Behavior
1. Create Button
2. A toast appears at the top with the message "Tree created."
3. Nothing (I have to refresh to see the tree)

## Possible Solution
1. Add the tree in the list
2. Redirect me to the new tree page

## Steps to Reproduce (for bugs)
Listed in the current behavior

## Your Environment

* Version used: IDK
* Browser name and version: Chrome Version 111.0.5563.64 (Official Build) (arm64)
* Operating System and version (desktop or mobile): macOS Ventura 13.0 (22A380)

**Comment by bienmag** [comment]
done!
